name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
  actions: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Pinned to a specific version for reproducibility
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-simple-blog==0.0.9
          pip install pillow cairosvg
          pip install mkdocs==1.6.1
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
